#!/usr/bin/env python

import sys

from rqt_vino_plugin.vino_graph import VinoGraph
from rqt_gui.main import Main

plugin = 'rqt_vino_plugin.vino_graph.VinoGraph'
main = Main()
sys.exit(main.main(standalone=plugin))
